# $Header$
#
# $Log$
# Revision 1.3  2004-12-19 16:38:13  tino
# new unit test version for builtin unit tests, prepare to integrate in tinolib
#
# Revision 1.2  2004/09/04 20:18:29  tino
# clean added
#
# Revision 1.1  2004/09/04 20:15:22  tino
# started to add unit tests

all:
	./tests.sh

clean:
	$(RM) -r TEST_* GEN *~
