container:
  image: gcc:latest

make_task:
  prep_script: apt-get update; apt-get install electric-fence
  compile_script: make test
  bugs_script: make log+bugs
  unit_tests_script: make log+unit
  warnings_script: make log+test
  should_fail_but_do_not_script: make log+info
  should_fail_and_fail_script: make log+fail
