container:
  image: gcc:latest

make_task:
  compile_script: make test
  post_compile: for UNIT_TEST/UNIT*/LOG.out; do [ -s "$a" ] || continue; printf '\n===== %q ======\n\n' "$a"; cat -nE "$a"; done
