make_task:
  matrix:
    - macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
    - container:
        image: gcc:latest
      prep_script: apt-get update; apt-get install electric-fence
  compile_script: make test
  bugs_script: make log+bug
  unit_tests_script: make log+unit
  warnings_script: make log+test
  not_failing_script: make log+info
  failing_script: make log+fail

