# $Header$
#
# $Log$
# Revision 1.1  2005-06-07 20:41:57  tino
# This support is nearly not tested and not complete yet
#

VERSION=1.2.2

    TARG=zlib
    BASE=$(TARG)-$(VERSION)

 URLPATH=http://www.gzip.org/zlib
 TARFILE=$(BASE).tar.bz2
  MD5SUM=1b8aab042d40979e456194c468fd72c5
   UNTAR=j

  LIBDIR=
  INCDIR=.
CCPREFIX=$(DIET)

    CONF=configure
CONFARGS=

include Makefile-gen
